function Hd = bandpass_filter
%BANDPASS_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 08-Feb-2022 16:31:01

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 120;  % Sampling Frequency

N    = 37;       % Order
Fc1  = 20;       % First Cutoff Frequency
Fc2  = 30;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hann(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);
% Set the arithmetic property.
set(Hd, 'Arithmetic', 'fixed', ...
    'CoeffWordLength', 14, ...
    'CoeffAutoScale', true, ...
    'Signed',         true, ...
    'InputWordLength', 14, ...
    'inputFracLength', 13, ...
    'FilterInternals',  'FullPrecision');
denormalize(Hd);


% [EOF]
