function Hd = filtro
%FILTRO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 07-Feb-2022 12:00:11

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 120000;  % Sampling Frequency

N    = 37;       % Order
Fc1  = 20000;    % First Cutoff Frequency
Fc2  = 30000;    % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hann(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
